name: Check data

on:
  schedule:
    - cron: "0 8 * * *" # 8 a.m. every day UTC
  workflow_dispatch:

jobs:
  check_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install notebook requests datetime pandas
    
    - name: Run image check
      run: jupyter execute check_imagery.ipynb
      
    - name: Add and commit results
      run: |
        git add .
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git commit -m "Latest data"

    - name: Push latest
      run: git push
